# My workflow
name : My first workflow

# on:
#   schedule:
#     -cron: '*/15 * * * *'

on : [ push, pull_request ]
# on:
#   push:
#     branches:
#       - main
#       - release/**
#   pull_request:
#     types: [ opened, assigned ]

jobs:
  job_1:
    name : My first job
    runs-on : ubuntu-latest
  # job_2:
  #   name : My second job
  #   needs : job_1
  # job_3:
  #   name : My third job
  #   needs : [job_1, job_2]
  
