# My workflow
name : My first workflow

# on:
#   schedule:
#     -cron: '*/15 * * * *'

on : [ push, pull_request ]
# on:
#   push:
#     branches:
#       - main
#       - release/**
#   pull_request:
#     types: [ opened, assigned ]

strategy:
  matrix:
    os-version : [ macos_latest, ubuntu_latest ]
    node_version : [10, 12, 14]
    
jobs:
  job_1:
    name : My first job
    runs-on : ${{ matrix.os_version }}
    steps:
      - uses : actions/setup-node@v2
        with:
          node-version : ${{ matrix.node_version }}
  # job_2:
  #   name : My second job
  #   needs : job_1
  # job_3:
  #   name : My third job
  #   needs : [job_1, job_2]
  
