# My workflow
name : My first workflow

# on:
#   schedule:
#     -cron: '*/15 * * * *'

on : [ push, pull_request ]
# on:
#   push:
#     branches:
#       - main
#       - release/**
#   pull_request:
#     types: [ opened, assigned ]

# strategy:
#   matrix:
#     os-version : [ macos_latest, ubuntu_latest ]
#     node_version : [10, 12, 14]
    
jobs:
  job_1:
    name : My first job
    runs-on : ubuntu-latest
    steps:
      - uses : actions/checkout@v3

      - name : Install python
        uses : actions/setup-python@v4
        with:
          python-version: '3.10'

      - name : call youtube api
        run : python main.py
        env :
          YOUTUBE: ${{ secrets.API_KEY }}
  # job_2:
  #   name : My second job
  #   needs : job_1
  # job_3:
  #   name : My third job
  #   needs : [job_1, job_2]
  
